/**
 * Core type definitions for chord data structures.
 *
 * @module types
 */

/**
 * A semitone interval within a single octave (0-11).
 * 0=C, 1=C#/Db, 2=D, ... 11=B
 */
export type IntervalNumber = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11

/**
 * Array of semitone intervals from the chord root, used for storage and playback.
 * Values can exceed 11 to span multiple octaves (e.g., 16 = one octave + major 3rd).
 */
export type Voicing = number[]

/**
 * 7-element array for the VoicingEditor UI, mapping to 7 grid columns.
 * Each element is the interval (0-11) for that column, or null for octave skip.
 * See utils/music/chords.ts for conversion functions.
 */
export type GridVoicing = (IntervalNumber | null)[]

/**
 * A chord definition for storage and playback.
 *
 * To calculate absolute MIDI notes: `root + voicing[i] + (octave * 12)`
 */
export interface ChordV1 {
  /** Display name (e.g., "Cmaj7"). Generated by getChordName(), not used for playback. */
  name: string
  /** Root note as semitone (0=C, 1=C#/Db, ... 11=B). Affects both naming and playback. */
  root: IntervalNumber
  /** Note intervals from root in semitones. Determines the chord's sound. */
  voicing: Voicing
  /** Base octave for MIDI output (4 = middle C octave). */
  octave: number
}

/**
 * Chord map file format for import/export.
 *
 * When adding new features requiring format changes, create ChordMapDefinitionV2.
 * Import should support both V1 and V2; export should use the latest version.
 */
export interface ChordMapDefinitionV1 {
  /** Chord slots array. Length must be divisible by 7 (columns). Null for empty slots. */
  chords: (ChordV1 | null)[]
  /** Format version. Must be 1 for this interface. */
  version: 1
}
